project:
  type: website

website:
  title: "Dateando"
  navbar:
    left:
      - text: Home
        href: index.html
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://github.com/miguel-conde
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
execute:
  freeze: auto
  
editor: visual

